name: Setup RelightLab Dependencies
description: Checkout, install Qt, MSVC, dependencies, and setup ccache

inputs:
  qt_version:
    description: 'Qt version to install'
    required: true
  checkout_ref:
    description: 'Git ref to checkout (optional)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ inputs.checkout_ref }}

    - name: Setup MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        version: ${{ inputs.qt_version }}

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y mesa-common-dev libglu1-mesa-dev 
        sudo apt-get install -y cmake ninja-build patchelf fuse libjpeg-dev libeigen3-dev
        sudo apt-get install -y libxcb-cursor0
        sudo apt-get install -y liblcms2-dev

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install coreutils libomp eigen libjpeg lcms2
        npm install -g appdmg

    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      shell: bash
      run: |
        C:/vcpkg/vcpkg.exe install lcms:x64-windows

    - name: Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-${{ github.ref }}
